#include "pos.h"
#include "app_time.h"
#include "fnd.h"
#include "joystick.h"
#include "lcd_ui.h"
#include "sensors.h"
#include "uart.h"
#include "ultrasonic.h"
#include <avr/interrupt.h>
#include <avr/io.h>
#include <string.h>
volatile pos_data_t g_pos_data={USER_NONE,0,0,0,0,0,0};
void __attribute__((weak)) pos_data_changed(const pos_data_t*data){(void)data;}void pos_get_snapshot(pos_data_t*out){if(!out)return;uint8_t s=SREG;cli();memcpy(out,(const void*)&g_pos_data,sizeof(*out));SREG=s;}static const char*user_text(user_mode_t m){return m==USER_CUSTOMER?"CUSTOMER":(m==USER_RIDER?"RIDER":"NONE");}static void changed(void){pos_data_t s;pos_get_snapshot(&s);pos_data_changed(&s);}static void counts(void){uart_puts("COUNT,A=");uart_put_u16(g_pos_data.count_a);uart_puts(",B=");uart_put_u16(g_pos_data.count_b);uart_puts(",C=");uart_put_u16(g_pos_data.count_c);uart_puts(",TOTAL=");uart_put_u16(g_pos_data.total_count);uart_newline();}static void emit_user(void){uart_puts("USER,");uart_puts(user_text(g_pos_data.user_mode));uart_newline();}static void done(void){uart_puts("PAY_DONE,USER=");uart_puts(user_text(g_pos_data.user_mode));uart_puts(",A=");uart_put_u16(g_pos_data.count_a);uart_puts(",B=");uart_put_u16(g_pos_data.count_b);uart_puts(",C=");uart_put_u16(g_pos_data.count_c);uart_puts(",TOTAL=");uart_put_u16(g_pos_data.total_count);uart_puts(",SESSION=");uart_put_u16(g_pos_data.session_id);uart_newline();}
static void reset_session(void){g_pos_data.user_mode=USER_NONE;g_pos_data.count_a=g_pos_data.count_b=g_pos_data.count_c=0;g_pos_data.total_count=0;g_pos_data.payment_done=0;g_pos_data.session_id++;fnd_set_zero();led_set(0);uart_puts("SESSION,START,ID=");uart_put_u16(g_pos_data.session_id);uart_newline();changed();}static void wait_person(void){lcd_ui_person_wait();uart_puts("EVT,WAIT_PERSON");uart_newline();while(!ultrasonic_is_near())app_delay_ms(60);uart_puts("HELLO");uart_newline();uart_puts("EVT,PERSON_DETECTED");uart_newline();lcd_ui_hello();app_delay_ms(300);}static void select_user(void){lcd_ui_user_select();uart_puts("EVT,SELECT_USER");uart_newline();joystick_wait_center();for(;;){joystick_event_t e=joystick_get_stable_event();if(e==JOY_RIGHT||e==JOY_LEFT){g_pos_data.user_mode=e==JOY_RIGHT?USER_CUSTOMER:USER_RIDER;emit_user();changed();return;}app_delay_ms(1);}}
static void add(char item){uint8_t*count=item=='A'?(uint8_t*)&g_pos_data.count_a:(item=='B'?(uint8_t*)&g_pos_data.count_b:(uint8_t*)&g_pos_data.count_c);(*count)++;uart_puts(item=='A'?"PAY:A":(item=='B'?"PAY:B":"PAY:C"));uart_newline();g_pos_data.total_count=g_pos_data.count_a+g_pos_data.count_b+g_pos_data.count_c;counts();changed();app_delay_ms(300);}static void finish(void){g_pos_data.total_count=g_pos_data.count_a+g_pos_data.count_b+g_pos_data.count_c;g_pos_data.payment_done=1;uart_puts("PAY_DONE");uart_newline();done();changed();fnd_set_total(g_pos_data.total_count);led_blink_done();app_delay_ms(500);}
void pos_run_forever(void){for(;;){reset_session();wait_person();select_user();uart_puts("EVT,WAIT_PRODUCT");uart_newline();for(;;){if(joystick_is_pressed()){joystick_wait_button_release();uart_puts("SESSION_RESET");uart_newline();break;}if(touch_done_pressed()){wait_touch_done_release();finish();break;}if(ir_product_detected()){uart_puts("EVT,PRODUCT_DETECTED");uart_newline();while(ir_product_detected()){if(touch_a_pressed()){add('A');wait_touch_a_release();break;}if(touch_b_pressed()){add('B');wait_touch_b_release();break;}if(touch_c_pressed()){add('C');wait_touch_c_release();break;}app_delay_ms(1);}while(ir_product_detected())app_delay_ms(1);uart_puts("EVT,WAIT_PRODUCT");uart_newline();}app_delay_ms(1);}}}
